# Generated by Django 4.2.7 on 2023-11-16 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='number',
            field=models.CharField(default=0, max_length=99, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
