# Generated by Django 4.2.7 on 2023-11-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_supplier_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=99, verbose_name='Descrição')),
                ('sector', models.CharField(blank=True, choices=[], max_length=20, null=True, verbose_name='Setor')),
                ('unit', models.CharField(blank=True, choices=[], max_length=5, null=True, verbose_name='Unidade')),
                ('manufacturer', models.CharField(max_length=99, verbose_name='Fabricante')),
                ('cost', models.PositiveIntegerField(default=0, verbose_name='Preço de Custo')),
                ('profit_margin', models.PositiveIntegerField(default=0, verbose_name='Margem de Lucro')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Quantidade mínima')),
                ('photo', models.ImageField(upload_to='base_static/img/products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='index.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
