# Generated by Django 4.2.7 on 2023-11-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profit_margin',
            field=models.PositiveIntegerField(default=30, verbose_name='Margem de Lucro'),
        ),
    ]
